# Generated by Django 2.2.3 on 2019-08-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
